export const NONE = "REACT/HEROES/NONE";
export const ADD_HERO = "REACT/HEROES/ADD_HERO";
export const REMOVE_HERO = "REACT/HEROES/REMOVE_HERO";
export const ADD_ABILITY_TO_HERO = "REACT/HEROES/ADD_ABILITY_TO_HERO";
export const REMOVE_ABILITY_TO_HERO = "REACT/HEROES/REMOVE_ABILITY_TO_HERO";